package view;

import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;

/**
 * Creates a VBox container with public access. It has all items needed for the
 * selectable section of the program
 * 
 * @author Peter Vukas
 *
 */
public class SelectionsBox extends VBox {
	/**
	 * A list of all the rows of elements, used in constructing the container
	 */
	private final HBox rows[] = { new HBox(), new HBox(), new HBox(), new HBox() };
	/**
	 * A list of all completed algorithms in a selectable form
	 */
	private final ComboBox<String> algorithmBox;
	/**
	 * An easy to enforce list of number of processes the user can select
	 */
	private final ComboBox<Integer> processNumBox;
	/**
	 * An easy to enforce list of quantum values users can select
	 */
	private final ComboBox<Integer> quantumBox;
	/**
	 * When selected, a process list will be autogenerated with random times.
	 */
	private Button randomizerBtn;
	/**
	 * Starts the calculation of the currently produced values.
	 */
	private Button startBtn;
	/**
	 * Label to tell the user what the algorithm box does.
	 */
	private final Label whatIsAlgorithmBox;
	/**
	 * Label to tell the user what the quantum box does.
	 */
	private final Label whatIsQuantumBox;
	/**
	 * Label to tell the user what the process box does.
	 */
	private final Label whatIsProcessBox;

	/**
	 * Creates a selections box with the specified limits.
	 * 
	 * @param maxProcesses
	 *            The maximum amount of processes the user can select
	 * @param maxQuantum
	 *            The maximum quantum value the user can select
	 */
	public SelectionsBox(int maxProcesses, int maxQuantum) {
		algorithmBox = new ComboBox<String>();
		algorithmBox.getItems().addAll("First in First Out", "Shortest Job First",
				// "Priority",
				// "Round Robin",
				"Shortest Remaining Time First");
		algorithmBox.setEditable(false); // Ensures the user can only select expected values.
		processNumBox = new ComboBox<Integer>();
		for (int i = 1; i <= maxProcesses; i++) {
			processNumBox.getItems().add(i);
		}
		processNumBox.setEditable(false);// Ensures the user can only select expected values.
		quantumBox = new ComboBox<Integer>();
		for (int i = 1; i <= maxQuantum; i++) {
			quantumBox.getItems().add(i);
		}
		quantumBox.setEditable(false);// Ensures the user can only select expected values.
		randomizerBtn = new Button("Autofill All Fields");
		startBtn = new Button("Calculate");
		whatIsAlgorithmBox = new Label("Select an Algorithm to use:");
		whatIsQuantumBox = new Label("Select a quantum value:");
		whatIsProcessBox = new Label("Select the number of processes:");

		// Construction of the container
		rows[0].getChildren().addAll(whatIsAlgorithmBox, algorithmBox);
		rows[1].getChildren().addAll(whatIsProcessBox, processNumBox);
		rows[2].getChildren().addAll(whatIsQuantumBox, quantumBox);
		rows[3].setSpacing(10);
		rows[3].getChildren().addAll(randomizerBtn, startBtn);
		getChildren().addAll(rows[0], rows[1], rows[2], rows[3]);
	}

	/**
	 * Enables or disables the quantum selector based on the opposite of the current
	 * value
	 */
	public void toggleQuantum() {
		rows[3].setDisable(!rows[3].isDisable());
	}

	/**
	 * @return The selected number of processes
	 */
	public int getNumberOfProcesses() {
		return processNumBox.getValue();
	}

	/**
	 * @return The selected quantum value or a -1 if this is called when the quantum
	 *         box is disabled
	 */
	public int getQuantum() {
		if (quantumBox.isDisable() == true) {
			return -1;
		}
		return quantumBox.getValue();
	}
}
